### ISSUE TITLE
Go package

### ISSUE THREAD

**Issue by steve0hh** [bhatiasiddharth/MIDAS#10]
Hey @bhatiasiddharth, very nice project and research.

Just letting you know that there is now implementation of [MIDAS in golang](https://github.com/steve0hh/midas).

If you have any feedback, let me know or feel free to create an issue on the project.

I've [bench-marked](https://github.com/steve0hh/midas/tree/master/examples) the AUC.py against this project using the darpa dataset and it's similar. :)

**Comment by bhatiasiddharth** [comment]
Thank you :)
The implementation looks great! I added a link to the README.
