### ISSUE TITLE
how to detect anomaly edges

### ISSUE THREAD

**Issue by zjf0822** [bhatiasiddharth/MIDAS#4]
hello, I have a question.
The output is anomaly score of edges,
but how to detect which edge is anomaly

And how to define the threashod of anomaly score

Thanks!

**Comment by bhatiasiddharth** [comment]
You can consider edges with high scores as anomalous. Right now we have not experimented with threshold for anomaly scores but it can be user-defined or implemented based on theorem in the paper.

**Comment by bhatiasiddharth** [comment]
You can consider edges with high scores as anomalous. Right now we have not experimented with threshold for anomaly scores but it can be user-defined or implemented based on the theorem in the paper.
