### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [bhatiasiddharth/MIDAS#5]
Hey, thanks for this project and research! Just wanted to let you know there are now [Ruby bindings](https://github.com/ankane/midas) for it. If you have any feedback, let me know or feel free to create an issue on the project.

**Comment by bhatiasiddharth** [comment]
Looks nice! Just added a link to the Ruby code in the README.

**Comment by ankane** [comment]
Awesome, thanks @bhatiasiddharth!
