### ISSUE TITLE
Why source and dest must be int?

### ISSUE THREAD

**Issue by rastafrange** [bhatiasiddharth/MIDAS#8]
Hello,

I was wondering why do we need to consider source and dest are int and not strings. Indeed, it would make more sense (to me) because usually, source and dest are IP addresses.
Thanks

**Comment by bhatiasiddharth** [comment]
Hi,

You are absolute right. Source and destination are usually IP addresses. We just map those strings to integer values to process them and have a fair comparison with the baseline. Our method can be extended to take input as strings as well.

Thanks.
