### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by rastafrange** [bhatiasiddharth/MIDAS#9]
Hello, I am currently trying to use MIDAS-R on a dataset however I have this error right after running it:

```
$ ./midas -i ../Wednesday-14-02-2018_4GRAPH.csv -o ../scores.txt
Finished Loading Data from ../Wednesday-14-02-2018_4GRAPH.csv
Segmentation fault: 11
```
Here is a sample of Wednesday-14-02-2018_4GRAPH.csv file:

source,destination,time
1451698946054,901943132206,352877
1451698946054,901943132206,628353
1451698946054,901943132206,973076
1451698946054,901943132206,980110
1451698946054,901943132206,981852
103079215137,1460288880642,1518566400
1322849927169,1047972020228,1518566400
1322849927169,1047972020228,1518566400
1322849927169,1047972020228,1518566400
687194767395,1640677507073,1518566400
1236950581249,1700807049228,1518566400
1322849927169,1047972020228,1518566400
1700807049228,712964571136,1518566400
1322849927169,1047972020228,1518566400
1632087572482,1477468749825,1518566400
1597727834115,94489280524,1518566400
1236950581249,979252543497,1518566400
1580547964930,979252543497,1518566400
1322849927169,1047972020228,1518566400
1116691496960,1047972020228,1518566401
1374389534736,163208757249,1518566401
1116691496960,1047972020228,1518566401
1520418422807,575525617668,1518566401

What is wrong?

Thanks

**Comment by bhatiasiddharth** [comment]
I am not getting a segmentation fault on my machine on this sample. Can you please share the entire file over email? I can try on that.
Range of int can be an issue. If possible, declare everything as long and try.

**Comment by rastafrange** [comment]
Okay I resolved it: I was keeping header and I saw on example.csv that the header should not be there ;)
